const MOVE_ENERGY = {
    "acid spray": 45,
    "acrobatics": 55,
    "aerial ace": 45,
    "aeroblast": 75,
    "air cutter": 35,
    "ancient power": 45,
    "aqua jet": 40,
    "aqua step": 40,
    "aqua tail": 35,
    "aura sphere": 40,
    "aura wheel": 45,
    "aura wheel": 45,
    "aurora beam": 60,
    "avalanche": 45,
    "beak blast": 55,
    "behemoth bash": 45,
    "behemoth blade": 55,
    "blast burn": 50,
    "blaze kick": 40,
    "bleakwind storm": 45,
    "blizzard": 75,
    "body slam": 35,
    "bone club": 35,
    "boomburst": 70,
    "brave bird": 55,
    "breaking swipe": 50,
    "brick break": 40,
    "brine": 50,
    "brutal swing": 35,
    "bubble beam": 40,
    "bug buzz": 60,
    "bulldoze": 45,
    "chilling water": 45,
    "clanging scales": 45,
    "close combat": 45,
    "crabhammer": 50,
    "cross chop": 35,
    "cross poison": 35,
    "crunch": 45,
    "crush grip": 50,
    "darkest lariat": 60,
    "dark pulse": 50,
    "dazzling gleam": 55,
    "dig": 50,
    "disarming voice": 45,
    "discharge": 40,
    "doom desire": 40,
    "double iron bash": 35,
    "draco meteor": 65,
    "dragon ascent": 70,
    "dragon claw": 50,
    "dragon energy": 45,
    "dragon pulse": 55,
    "draining kiss": 55,
    "drain punch": 40,
    "drill peck": 40,
    "drill run": 45,
    "drum beating": 35,
    "dynamax cannon": 45,
    "dynamic punch": 45,
    "earthquake": 65,
    "earth power": 55,
    "energy ball": 55,
    "feather dance": 50,
    "fell stinger": 35,
    "fire blast": 80,
    "fire punch": 40,
    "flamethrower": 55,
    "flame burst": 55,
    "flame charge": 50,
    "flame wheel": 45,
    "flash cannon": 70,
    "flower trick": 35,
    "fly": 45,
    "flying press": 40,
    "focus blast": 75,
    "foul play": 40,
    "freeze shock": 60,
    "frenzy plant": 45,
    "frustration": 70,
    "fusion bolt": 45,
    "fusion flare": 45,
    "future sight": 65,
    "giga drain": 80,
    "giga impact": 80,
    "gigaton hammer": 60,
    "glaciate": 40,
    "grass knot": 50,
    "gunk shot": 75,
    "gyro ball": 50,
    "heart stamp": 40,
    "heat wave": 45,
    "heavy slam": 50,
    "high horsepower": 60,
    "high jump kick": 55,
    "horn attack": 35,
    "hurricane": 65,
    "hydro cannon": 40,
    "hydro pump": 75,
    "hydro pump blastoise": 80,
    "hyper beam": 80,
    "hyper fang": 50,
    "ice beam": 55,
    "ice burn": 60,
    "ice punch": 40,
    "icicle spear": 40,
    "icy wind": 45,
    "iron head": 50,
    "last resort": 55,
    "leaf blade": 35,
    "leaf storm": 55,
    "leaf tornado": 40,
    "liquidation": 45,
    "low sweep": 40,
    "lunge": 45,
    "luster purge": 60,
    "magma storm": 40,
    "magnet bomb": 45,
    "megahorn": 55,
    "mega drain": 55,
    "meteor beam": 60,
    "meteor mash": 45,
    "mind blown": 35,
    "mirror coat": 55,
    "mirror shot": 35,
    "mist ball": 60,
    "moonblast": 60,
    "moongeist beam": 65,
    "muddy water": 35,
    "mud bomb": 45,
    "mystical fire": 45,
    "nature's madness": 50,
    "night shade": 45,
    "night slash": 35,
    "oblivion wing": 50,
    "obstruct": 40,
    "octazooka": 50,
    "ominous wind": 45,
    "origin pulse": 60,
    "outrage": 60,
    "overheat": 55,
    "parabolic charge": 50,
    "payback": 60,
    "petal blizzard": 65,
    "play rough": 60,
    "poison fang": 40,
    "poltergeist": 75,
    "power gem": 50,
    "power-up punch": 35,
    "power whip": 50,
    "precipice blades": 60,
    "psybeam": 60,
    "psychic": 55,
    "psychic fangs": 35,
    "psycho boost": 35,
    "psyshock": 40,
    "psystrike": 45,
    "pyro ball": 40,
    "rage fist": 35,
    "razor shell": 35,
    "rest": 35,
    "return": 70,
    "roar of time": 65,
    "rock blast": 40,
    "rock slide": 45,
    "rock tomb": 50,
    "rock wrecker": 50,
    "sacred fire": 65,
    "sacred sword": 35,
    "sandsear storm": 45,
    "sand tomb": 40,
    "scald": 50,
    "scorching sands": 50,
    "secret sword": 35,
    "seed bomb": 40,
    "seed flare": 75,
    "shadow ball": 50,
    "shadow bone": 45,
    "shadow force": 90,
    "shadow punch": 35,
    "shadow sneak": 50,
    "signal beam": 55,
    "silver wind": 45,
    "skull bash": 75,
    "sky attack": 50,
    "sludge": 40,
    "sludge bomb": 50,
    "sludge wave": 65,
    "solar beam": 80,
    "spacial rend": 55,
    "sparkling aria": 45,
    "spirit shackle": 40,
    "springtide storm (speculative)": 45,
    "stomp": 40,
    "stone edge": 55,
    "struggle": 100,
    "submission": 50,
    "sunsteel strike": 65,
    "superpower": 40,
    "surf": 45,
    "swift": 35,
    "synchronoise": 50,
    "techno blast (burn)": 55,
    "techno blast (chill)": 55,
    "techno blast (douse)": 55,
    "techno blast (normal)": 55,
    "techno blast (shock)": 55,
    "thunder": 60,
    "thunderbolt": 55,
    "thunder cage": 40,
    "thunder punch": 40,
    "torch song": 45,
    "trailblaze": 45,
    "triple axel": 45,
    "tri attack": 50,
    "twister": 40,
    "upper hand": 40,
    "vise grip": 40,
    "volt tackle": 40,
    "v-create": 40,
    "water pulse": 50,
    "weather ball (fire)": 35,
    "weather ball (ice)": 35,
    "weather ball (normal)": 35,
    "weather ball (rock)": 35,
    "weather ball (water)": 35,
    "wildbolt storm": 45,
    "wild charge": 45,
    "wrap": 45,
    "x-scissor": 40,
    "zap cannon": 80,
};
